#--bat
[".config/bat/syntaxes/just_sublime"]
type = "git-repo"
url = "https://github.com/nk9/just_sublime.git"

[".config/bat/themes/Catppuccin Mocha.tmTheme"]
type = "file"
url = "https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Mocha.tmTheme"
